objects/Batch_Job_Schedule__c.object
<CustomObject>
    <description>Batch Apex Job Schedule</description>
    <fields>
        <fullName>Cron_Expression__c</fullName>
        <label>Cron Expression</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Every_Number_of_Days__c</fullName>
        <label>Every Number of Day(s)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Every_Number_of_Hours__c</fullName>
        <label>Every Number of Hour(s)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Every_Number_of_Months__c</fullName>
        <label>Every Number of Month(s)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Preferred_Start_Day__c</fullName>
        <label>Preferred Start Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Start_Hour__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <label>Preferred Start Hour</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <default>true</default>
                    <label>0AM</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>1AM</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>2AM</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3AM</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>4AM</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>5AM</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>6AM</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>7AM</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>8AM</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <label>9AM</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10AM</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>11AM</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <label>12PM</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>13PM</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>14PM</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <label>15PM</label>
                </value>
                <value>
                    <fullName>16</fullName>
                    <label>16PM</label>
                </value>
                <value>
                    <fullName>17</fullName>
                    <label>17PM</label>
                </value>
                <value>
                    <fullName>18</fullName>
                    <label>18PM</label>
                </value>
                <value>
                    <fullName>19</fullName>
                    <label>19PM</label>
                </value>
                <value>
                    <fullName>20</fullName>
                    <label>20PM</label>
                </value>
                <value>
                    <fullName>21</fullName>
                    <label>21PM</label>
                </value>
                <value>
                    <fullName>22</fullName>
                    <label>22PM</label>
                </value>
                <value>
                    <fullName>23</fullName>
                    <label>23PM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Start_Minute__c</fullName>
        <label>Preferred Start Minute</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Start_Month__c</fullName>
        <label>Preferred Start Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Start_Week_Day__c</fullName>
        <label>Preferred Start Week Day</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MON</fullName>
                    <label>Monday</label>
                </value>
                <value>
                    <fullName>TUE</fullName>
                    <label>Tuesday</label>
                </value>
                <value>
                    <fullName>WED</fullName>
                    <label>Wednesday</label>
                </value>
                <value>
                    <fullName>THU</fullName>
                    <label>Thursday</label>
                </value>
                <value>
                    <fullName>FRI</fullName>
                    <label>Friday</label>
                </value>
                <value>
                    <fullName>SAT</fullName>
                    <label>Saturday</label>
                </value>
                <value>
                    <fullName>SUN</fullName>
                    <label>Sunday</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Batch Job Schedule</label>
    <nameField>
        <label>Batch Job Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Job Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SchedulerCronExpressionHandler.cls
public class SchedulerCronExpressionHandler {
    
    public static void execute(List<Batch_Job_Schedule__c> batchJobSchedules) {
        for(Batch_Job_Schedule__c sch :batchJobSchedules) {
            if(sch.RecordTypeId == GlobalConstants.SCHEDULER_RECORD_TYPE_HOURLY_JOB)
                sch.Cron_Expression__c = String.format('0 {0} 0/{1} 1/1 * ? *', 
                                                       new List<String>{sch.Preferred_Start_Minute__c, 
                                                                        String.valueOf(sch.Every_Number_of_Hours__c)}); 
            else if(sch.RecordTypeId == GlobalConstants.SCHEDULER_RECORD_TYPE_DAILY_JOB)
                sch.Cron_Expression__c = String.format('0 {0} {1} 1/{2} * ? *', 
                                                       new List<String>{sch.Preferred_Start_Minute__c, 
                                                                        sch.Preferred_Start_Hour__c,
                                                                        String.valueOf(sch.Every_Number_of_Days__c)}); 
            else if(sch.RecordTypeId == GlobalConstants.SCHEDULER_RECORD_TYPE_WEEKLY_JOB)
                sch.Cron_Expression__c = String.format('0 {0} {1} ? * {2} *', 
                                                       new List<String>{sch.Preferred_Start_Minute__c, 
                                                                        sch.Preferred_Start_Hour__c,
                                                                        sch.Preferred_Start_Week_Day__c.replace(';', ',')}); 
            else if(sch.RecordTypeId == GlobalConstants.SCHEDULER_RECORD_TYPE_MONTHLY_JOB)
                sch.Cron_Expression__c = String.format('0 {0} {1} {2} 1/{3} ? *', 
                                                       new List<String>{sch.Preferred_Start_Minute__c, 
                                                                        sch.Preferred_Start_Hour__c,
                                                                        sch.Preferred_Start_Day__c,
                                                                        String.valueOf(sch.Every_Number_of_Months__c)}); 
            else if(sch.RecordTypeId == GlobalConstants.SCHEDULER_RECORD_TYPE_YEARLY_JOB)
                sch.Cron_Expression__c = String.format('0 {0} {1} {2} {3} ? *', 
                                                       new List<String>{sch.Preferred_Start_Minute__c, 
                                                                        sch.Preferred_Start_Hour__c,
                                                                        sch.Preferred_Start_Day__c,
                                                                        sch.Preferred_Start_Month__c}); 
            
        }
    }

}