objects/Batch_Job_Schedule__c.object
<CustomObject>
    <description>Batch Apex Job Schedule</description>
    <fields>
        <fullName>Cron_Expression__c</fullName>
        <label>Cron Expression</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cron_Trigger_Id__c</fullName>
        <description>Scheduled Job Cron Trigger Id</description>
        <inlineHelpText>Scheduled Job Cron Trigger Id</inlineHelpText>
        <label>Cron Trigger Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Every_Number_of_Days__c</fullName>
        <label>Every Number of Day(s)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Every_Number_of_Hours__c</fullName>
        <label>Every Number of Hour(s)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Every_Number_of_Months__c</fullName>
        <label>Every Number of Month(s)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Preferred_Start_Day__c</fullName>
        <label>Preferred Start Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Start_Hour__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <label>Preferred Start Hour</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <default>true</default>
                    <label>0AM</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>1AM</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>2AM</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3AM</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>4AM</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>5AM</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>6AM</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>7AM</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>8AM</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <label>9AM</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10AM</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>11AM</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <label>12PM</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>13PM</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>14PM</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <label>15PM</label>
                </value>
                <value>
                    <fullName>16</fullName>
                    <label>16PM</label>
                </value>
                <value>
                    <fullName>17</fullName>
                    <label>17PM</label>
                </value>
                <value>
                    <fullName>18</fullName>
                    <label>18PM</label>
                </value>
                <value>
                    <fullName>19</fullName>
                    <label>19PM</label>
                </value>
                <value>
                    <fullName>20</fullName>
                    <label>20PM</label>
                </value>
                <value>
                    <fullName>21</fullName>
                    <label>21PM</label>
                </value>
                <value>
                    <fullName>22</fullName>
                    <label>22PM</label>
                </value>
                <value>
                    <fullName>23</fullName>
                    <label>23PM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Start_Minute__c</fullName>
        <label>Preferred Start Minute</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Start_Month__c</fullName>
        <label>Preferred Start Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Start_Week_Day__c</fullName>
        <label>Preferred Start Week Day</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MON</fullName>
                    <label>Monday</label>
                </value>
                <value>
                    <fullName>TUE</fullName>
                    <label>Tuesday</label>
                </value>
                <value>
                    <fullName>WED</fullName>
                    <label>Wednesday</label>
                </value>
                <value>
                    <fullName>THU</fullName>
                    <label>Thursday</label>
                </value>
                <value>
                    <fullName>FRI</fullName>
                    <label>Friday</label>
                </value>
                <value>
                    <fullName>SAT</fullName>
                    <label>Saturday</label>
                </value>
                <value>
                    <fullName>SUN</fullName>
                    <label>Sunday</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Batch Job Schedule</label>
    <nameField>
        <label>Batch Job Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Job Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SchedulerCronExpressionHandlerTest.cls
/*
Copyright (c) Ian Huang Salesforce
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
OR OTHER DEALINGS IN THE SOFTWARE.
*/
@isTest
private class SchedulerCronExpressionHandlerTest {

   @isTest
    static void testHourlyJob() {
        Test.startTest();
        
        Batch_Job_Schedule__c sch = new Batch_Job_Schedule__c();
        sch.RecordTypeId = GlobalConstants.SCHEDULER_RECORD_TYPE_HOURLY_JOB;
        sch.Name = 'Test Hourly Name 001';
        sch.Every_Number_of_Hours__c = 1;
        sch.Preferred_Start_Minute__c = '0';
        insert sch;
        
        Test.stopTest();
        
        Batch_Job_Schedule__c jobSch = [SELECT Id, Cron_Expression__c FROM Batch_Job_Schedule__c][0];
        System.assertEquals('0 0 0/1 1/1 * ? *', jobSch.Cron_Expression__c);
    }
    
    @isTest
    static void testDailyJob() {
        Test.startTest();
        
        Batch_Job_Schedule__c sch = new Batch_Job_Schedule__c();
        sch.RecordTypeId = GlobalConstants.SCHEDULER_RECORD_TYPE_DAILY_JOB;
        sch.Name = 'Test Daily Name 001';
        sch.Every_Number_of_Days__c = 1;
        sch.Preferred_Start_Hour__c = '2';
        sch.Preferred_Start_Minute__c = '1';
        insert sch;
        
        Test.stopTest();

        Batch_Job_Schedule__c jobSch = [SELECT Id, Cron_Expression__c FROM Batch_Job_Schedule__c][0];
        System.assertEquals('0 1 2 1/1 * ? *', jobSch.Cron_Expression__c);
    }
    
    @isTest
    static void testWeeklyJob() {
        Test.startTest();
        
        Batch_Job_Schedule__c sch = new Batch_Job_Schedule__c();
        sch.RecordTypeId = GlobalConstants.SCHEDULER_RECORD_TYPE_WEEKLY_JOB;
        sch.Name = 'Test Weekly Name 001';
        sch.Preferred_Start_Week_Day__c = 'MON;TUE;WED';
        sch.Preferred_Start_Hour__c = '3';
        sch.Preferred_Start_Minute__c = '2';
        insert sch;
        
        Test.stopTest();

        Batch_Job_Schedule__c jobSch = [SELECT Id, Cron_Expression__c FROM Batch_Job_Schedule__c][0];
        System.assertEquals('0 2 3 ? * MON,TUE,WED *', jobSch.Cron_Expression__c);
    }
    
    @isTest
    static void testMonthlyJob() {
        Test.startTest();
        
        Batch_Job_Schedule__c sch = new Batch_Job_Schedule__c();
        sch.RecordTypeId = GlobalConstants.SCHEDULER_RECORD_TYPE_MONTHLY_JOB;
        sch.Name = 'Test Monthly Name 001';
        sch.Every_Number_of_Months__c = 3;
        sch.Preferred_Start_Day__c = '5';
        sch.Preferred_Start_Hour__c = '4';
        sch.Preferred_Start_Minute__c = '3';
        insert sch;
        
        Test.stopTest();
        
        Batch_Job_Schedule__c jobSch = [SELECT Id, Cron_Expression__c FROM Batch_Job_Schedule__c][0];
        System.assertEquals('0 3 4 5 1/3 ? *', jobSch.Cron_Expression__c);
    }

    @isTest
    static void testYearlyJob() {
        Test.startTest();
        
        Batch_Job_Schedule__c sch = new Batch_Job_Schedule__c();
        sch.RecordTypeId = GlobalConstants.SCHEDULER_RECORD_TYPE_YEARLY_JOB;
        sch.Name = 'Test Yearly Name 001';
        sch.Preferred_Start_Month__c = 'December';
        sch.Preferred_Start_Day__c = '5';
        sch.Preferred_Start_Hour__c = '4';        
        sch.Preferred_Start_Minute__c = '4';
        insert sch;
        
        Test.stopTest();

        Batch_Job_Schedule__c jobSch = [SELECT Id, Cron_Expression__c FROM Batch_Job_Schedule__c][0];
        System.assertEquals('0 4 4 5 December ? *', jobSch.Cron_Expression__c);
    }

    @isTest
    static void testCustomCronExpressionJob() {
        Test.startTest();
        
        Batch_Job_Schedule__c sch = new Batch_Job_Schedule__c();
        sch.RecordTypeId = GlobalConstants.SCHEDULER_RECORD_TYPE_CUSTOM_CRON_EXPRESSION_JOB;
        sch.Name = 'Test Custom Name 001';
        sch.Cron_Expression__c = '0 0 1 3 */3 ? 2029-2030';
        insert sch;
        
        Test.stopTest();
        
        Batch_Job_Schedule__c jobSch = [SELECT Id, Cron_Expression__c FROM Batch_Job_Schedule__c][0];
        System.assertEquals('0 0 1 3 */3 ? 2029-2030', jobSch.Cron_Expression__c);
    }

    @isTest
    static void testExistingJob() {
        Test.startTest();
        
        Batch_Job_Schedule__c sch = new Batch_Job_Schedule__c();
        sch.RecordTypeId = GlobalConstants.SCHEDULER_RECORD_TYPE_EXISTING_SHCEDULED_JOB_JOB;
        sch.Name = 'Test Existing Job Name 001';
        String jobId = System.schedule('15 Mins Batch Jobs', '0 0 12 1/1 * ? *', new BatchJobScheduler());
        sch.Cron_Trigger_Id__c = jobId;
        sch.Cron_Expression__c = '0 0 12 1/1 * ? *';
        insert sch;
        
        Test.stopTest();
        
        Batch_Job_Schedule__c jobSch = [SELECT Id, Cron_Expression__c FROM Batch_Job_Schedule__c][0];
        System.assertEquals('0 0 12 1/1 * ? *', jobSch.Cron_Expression__c);
    }

}