objects/Batch_Job_Schedule__c.object
<CustomObject>
    <description>Batch Apex Job Schedule</description>
    <fields>
        <fullName>Every_Number_of_Hours__c</fullName>
        <label>Every Number of Hour(s)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Every_Number_of_Months__c</fullName>
        <label>Every Number of Month(s)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Preferred_Start_Day__c</fullName>
        <label>Preferred Start Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Start_Hour__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <label>Preferred Start Hour</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <default>true</default>
                    <label>0AM</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>1AM</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>2AM</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3AM</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>4AM</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>5AM</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>6AM</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>7AM</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>8AM</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <label>9AM</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>10AM</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>11AM</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <label>12PM</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>13PM</label>
                </value>
                <value>
                    <fullName>14</fullName>
                    <label>14PM</label>
                </value>
                <value>
                    <fullName>15</fullName>
                    <label>15PM</label>
                </value>
                <value>
                    <fullName>16</fullName>
                    <label>16PM</label>
                </value>
                <value>
                    <fullName>17</fullName>
                    <label>17PM</label>
                </value>
                <value>
                    <fullName>18</fullName>
                    <label>18PM</label>
                </value>
                <value>
                    <fullName>19</fullName>
                    <label>19PM</label>
                </value>
                <value>
                    <fullName>20</fullName>
                    <label>20PM</label>
                </value>
                <value>
                    <fullName>21</fullName>
                    <label>21PM</label>
                </value>
                <value>
                    <fullName>22</fullName>
                    <label>22PM</label>
                </value>
                <value>
                    <fullName>23</fullName>
                    <label>23PM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Start_Minute__c</fullName>
        <label>Preferred Start Minute</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Start_Month__c</fullName>
        <label>Preferred Start Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Batch Job Schedule</label>
    <nameField>
        <label>Batch Job Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Job Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SchedulerConfigurationControllerTest.cls
@isTest
private class SchedulerConfigurationControllerTest {

    @testSetup static void setup() {
        
        Batch_Job_Schedule__c sch1 = new Batch_Job_Schedule__c();
        sch1.RecordTypeId = GlobalConstants.SCHEDULER_RECORD_TYPE_HOURLY_JOB;
        sch1.Name = 'Test Hourly Name 001';
        sch1.Every_Number_of_Hours__c = 1;
        sch1.Preferred_Start_Minute__c = '0';
        
        Batch_Job_Schedule__c sch2 = new Batch_Job_Schedule__c();
        sch2.RecordTypeId = GlobalConstants.SCHEDULER_RECORD_TYPE_MONTHLY_JOB;
        sch2.Name = 'Test Monthly Name 001';
        sch2.Every_Number_of_Months__c = 3;
        sch2.Preferred_Start_Day__c = '5';
        sch2.Preferred_Start_Hour__c = '4';
        sch2.Preferred_Start_Minute__c = '3';
        
        Batch_Job_Schedule__c sch3 = new Batch_Job_Schedule__c();
        sch3.RecordTypeId = GlobalConstants.SCHEDULER_RECORD_TYPE_YEARLY_JOB;
        sch3.Name = 'Test Yearly Name 001';
        sch3.Preferred_Start_Month__c = 'December';
        sch3.Preferred_Start_Minute__c = '4';
        
        insert new List<Batch_Job_Schedule__c>{sch1, sch2, sch3};
    }
    
    @isTest
    static void testLoad() {
        PageReference pageRef = Page.SchedulerConfiguration;
        Test.setCurrentPage(pageRef);
      
        SchedulerConfigurationController controller = new SchedulerConfigurationController();
        
        System.assertEquals(3, controller.scheduledApexJobs.size());
    }
    
    @isTest
    static void testSave() {
        PageReference pageRef = Page.SchedulerConfiguration;
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        
        SchedulerConfigurationController controller = new SchedulerConfigurationController();
        controller.scheduledApexJobs[0].scheduled = true;
        controller.save();

        controller.scheduledApexJobs[0].scheduled = false;
        controller.save();
        
        Test.stopTest();
        
        System.assertEquals(3, controller.scheduledApexJobs.size());
        System.assertEquals(false, controller.scheduledApexJobs[0].scheduled);
    }

}