objects/Batch_Apex_Job__c.object
<CustomObject>
    <description>Batch Apex jobs managed by Batch Job Scheduler</description>
    <fields>
        <fullName>Batch_Class_Name__c</fullName>
        <description>Apex batch class name</description>
        <inlineHelpText>Batch Apex class name</inlineHelpText>
        <label>Batch Class Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Batch_Group__c</fullName>
        <description>Group of batch jobs running together</description>
        <inlineHelpText>Group of batch jobs</inlineHelpText>
        <label>Batch Group</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Batch_Job_Schedule__c</fullName>
        <description>Parent Batch Job Schedule</description>
        <label>Batch Job Schedule</label>
        <referenceTo>Batch_Job_Schedule__c</referenceTo>
        <relationshipLabel>Batch Apex Jobs</relationshipLabel>
        <relationshipName>Batch_Apex_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether the Batch Apex job will be executed</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Batch Apex Job</label>
    <nameField>
        <displayFormat>JOB-{000000}</displayFormat>
        <label>Batch Apex Job No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Batch_Job_Log__c.object
<CustomObject>
    <description>Apex Batch Job Log</description>
    <label>Batch Job Log</label>
    <nameField>
        <displayFormat>BJL-{0000000}</displayFormat>
        <label>Batch Job Log No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Job Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Batch_Job_Schedule__c.object
<CustomObject>
    <description>Batch Apex Job Schedule</description>
    <fields>
        <fullName>Every_Number_of_Hours__c</fullName>
        <label>Every Number of Hour(s)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Preferred_Start_Minute__c</fullName>
        <label>Preferred Start Minute</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Batch Job Schedule</label>
    <nameField>
        <label>Batch Job Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Job Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchJobSchedulerTest.cls
@isTest
private class BatchJobSchedulerTest {

    @testSetup static void setup() {
        
        Batch_Job_Schedule__c sch = new Batch_Job_Schedule__c();
        sch.RecordTypeId = GlobalConstants.SCHEDULER_RECORD_TYPE_HOURLY_JOB;
        sch.Name = 'Test Hourly Name 001';
        sch.Every_Number_of_Hours__c = 1;
        sch.Preferred_Start_Minute__c = '0';
        insert sch;

        Batch_Apex_Job__c batchJob1 = new Batch_Apex_Job__c(Batch_Job_Schedule__c=sch.Id, Batch_Class_Name__c='TestBatchJob1',
                                                            Batch_Group__c='1', Enabled__c=true);
        Batch_Apex_Job__c batchJob2 = new Batch_Apex_Job__c(Batch_Job_Schedule__c=sch.Id, Batch_Class_Name__c='TestBatchJob2',
                                                            Batch_Group__c='1', Enabled__c=true);
        Batch_Apex_Job__c batchJob3 = new Batch_Apex_Job__c(Batch_Job_Schedule__c=sch.Id, Batch_Class_Name__c='TestBatchJob3',
                                                            Batch_Group__c='2', Enabled__c=true);
        insert new List<Batch_Apex_Job__c>{batchJob1, batchJob2, batchJob3};
 
        Account account1 = new Account(Name='__BatchJobSchedulerTest001', Type='_BJS_Testing_');
        Account account2 = new Account(Name='__BatchJobSchedulerTest002', Type='_BJS_Testing_');
        Account account3 = new Account(Name='__BatchJobSchedulerTest003', Type='_BJS_Testing_');
        insert new List<Account>{account1, account2, account3};
    }

    @isTest
    static void testExecute() {
        Id cronTriggerId = System.schedule('test job.schedule.Name', '0 3 4 5 1/3 ? *', new BatchJobScheduler());
        
        BatchJobScheduler batchJobScheduler = new BatchJobScheduler();
        batchJobScheduler.executeJobs(cronTriggerId);
        
        List<Account> accounts = [SELECT Id, Type FROM Account];
        System.assertEquals(3, accounts.size());
        System.assertEquals('_BJS_Testing_', accounts[0].Type);
        System.assertEquals('_BJS_Testing_', accounts[1].Type);
        System.assertEquals('_BJS_Testing_', accounts[2].Type);
    }    

    @isTest
    static void testExecuteNext() {
        
        Id cronTriggerId = System.schedule('test job.schedule.Name', '0 3 4 5 1/3 ? *', new BatchJobScheduler());
        
        BatchJobScheduler batchJobScheduler = new BatchJobScheduler();
        batchJobScheduler.executeJobs(cronTriggerId);
        batchJobScheduler.executeNextJob('TestBatchJob1');
        
        List<Account> accounts = [SELECT Id, Type FROM Account];
        System.assertEquals(3, accounts.size());
        System.assertEquals('_BJS_Testing_', accounts[0].Type);
        System.assertEquals('_BJS_Testing_', accounts[1].Type);
        System.assertEquals('_BJS_Testing_', accounts[2].Type);
    }

    @isTest
    static void testlogBatchJob() {
        BatchJobHelper.logBatchJob('batchJobName', System.now(), 'errorMessages');
        
        List<Batch_Job_Log__c> logs = [SELECT Id FROM Batch_Job_Log__c];
        System.assertEquals(1, logs.size());
    }
    
    @isTest
    static void testBatchJob1() {
        Test.startTest();
        Database.executeBatch(new TestBatchJob1());
        Test.stopTest();

        List<Account> accounts = [SELECT Id, Type FROM Account];
        System.assertEquals(3, accounts.size());
        System.assertEquals('Prospect', accounts[0].Type);
        System.assertEquals('Prospect', accounts[1].Type);
        System.assertEquals('Prospect', accounts[2].Type);
    }
    
    @isTest
    static void testBatchJob2() {
        Test.startTest();
        Database.executeBatch(new TestBatchJob2());
        Test.stopTest();

        List<Account> accounts = [SELECT Id, Type FROM Account];
        System.assertEquals(3, accounts.size());
        System.assertEquals('Prospect', accounts[0].Type);
        System.assertEquals('Prospect', accounts[1].Type);
        System.assertEquals('Prospect', accounts[2].Type);
    }
    
    @isTest
    static void testBatchJob3() {
        Test.startTest();
        Database.executeBatch(new TestBatchJob3());
        Test.stopTest();

        List<Account> accounts = [SELECT Id, Type FROM Account];
        System.assertEquals(3, accounts.size());
        System.assertEquals('Prospect', accounts[0].Type);
        System.assertEquals('Prospect', accounts[1].Type);
        System.assertEquals('Prospect', accounts[2].Type);
    }

}