objects/Batch_Job_Log__c.object
<CustomObject>
    <description>Apex Batch Job Log</description>
    <fields>
        <fullName>Batch_Job_Name__c</fullName>
        <description>Apex Batch Job class name</description>
        <label>Batch Job Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <description>Batch job completed time</description>
        <label>Completed Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Execution_Result__c</fullName>
        <label>Execution Result</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Batch Job Log</label>
    <nameField>
        <displayFormat>BJL-{0000000}</displayFormat>
        <label>Batch Job Log No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Job Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchJobHelper.cls
/*------------------------------------------------------------
Author:        Ian Huang
Company:       Salesforce
Description:   Batch Job Log helper class, Objects: Batch_Job_Log__c
History:       2015-11-19   Ian Huang   Created.    
------------------------------------------------------------*/
public inherited sharing class BatchJobHelper {
    
    //Log batch job exection result
    public static void logBatchJob(String batchJobName, Database.BatchableContext BC) {
        logBatchJob(batchJobName, BC, '');
    }
    
    //Log batch job exection result
    public static void logBatchJob(String batchJobName, Database.BatchableContext BC, String summary) {
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CompletedDate, CreatedBy.Email, ExtendedStatus 
                            FROM   AsyncApexJob 
                            WHERE  Id =:BC.getJobId()];

        String executeResult = 'JobItemsProcessed: ' + job.JobItemsProcessed
                               + '\nNumberOfErrors: ' + job.NumberOfErrors + '\nStatus: '
                               + job.Status + '\nExtendedStatus: ' + job.ExtendedStatus;

        // Create a batch job log record to notify the batch job execute result
        try {
            Batch_Job_Log__c bjl = new Batch_Job_Log__c(
                Batch_Job_Name__c = batchJobName,
                Completed_Date__c = job.CompletedDate,
                Execution_Result__c = executeResult + '\n' + summary);
            insert bjl;
        } catch (Exception ex) {
            throw new DmlException('Failed to save batch job log: ' + ex.getMessage());          
        }
    }

    //Log batch job exection result
    public static void logBatchJob(String batchJobName, DateTime completedDate, String errorMessages) {
        // Create a batch job log record to notify the batch job execute result
        try {
            Batch_Job_Log__c bjl = new Batch_Job_Log__c(
                Batch_Job_Name__c = batchJobName,
                Completed_Date__c = completedDate,
                Execution_Result__c = errorMessages);
            insert bjl;
        } catch (Exception ex) {
            throw new DmlException('Failed to save batch job log. ' + ex.getMessage());          
        }
    }
}